theme: jekyll-theme-minimal
title: Kyunghoon Han CS-3353-01 Arch Installation Documentation
description: Documentation of Arch Installtion

Instruct(1): 1) To start, one must download the Arch Linux through a type of medium (whether that medium be a USB drive and such) using the available wiki

Instruct(2): 2) Once you have access and installed Arch into a virtual machine, make sure, if using VMWare Workstation, to head for the directory in order to boot into UEFI mode by inserting
Instruct(2):    fireware= efi (must have quotation marks around efi) into line 2 of the .vmx file (recommend using Notepad and make sure to have the VMWare Workstation off while making said change).

Instruct(3): 3) After installation, we must install items into sda2 (virtual machine), with sda1 being the EFI partition and sda2 as the main installation.
Instruct(3):    To first create the sda(s), we must run fdisk -l to find the name of the disk to partition. Use the following command cfdisk /dev/sda. For the following options that requires
Instruct(3):    the label type, should one intends to use GRUB to boot, then select GPT for this current example.

Instruct(4): 4) Partition using fdisk gives 4 options in regards to labels: gpt, dos, sgi, sun; After deciding which one would work with the given bootinstaller, then you are
Instruct(4):    given chance to create the necessary paritions with whatever free space is available to create said partitions with necessary types.
   

